name: MK Modular Remix Development
description: Project board for tracking development of MK Modular Remix

columns:
  - name: 📋 Backlog
    description: Items that need to be worked on
    
  - name: 🎯 Sprint Planning
    description: Items planned for current sprint
    
  - name: ⏳ In Progress
    description: Currently being worked on
    
  - name: 🔍 Review
    description: Ready for review/testing
    
  - name: ✅ Done
    description: Completed items

labels:
  - name: bug
    color: d73a4a
    description: Something isn't working
    
  - name: enhancement
    color: a2eeef
    description: New feature or request
    
  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation
    
  - name: test
    color: 0e8a16
    description: Testing related changes
    
  - name: ci-cd
    color: fbca04
    description: CI/CD pipeline changes

milestones:
  - title: Phase 1 - Foundations
    description: Setting up project foundations and testing infrastructure
    
  - title: Phase 2 - Architecture
    description: Implementing architectural improvements
    
  - title: Phase 3 - DevOps
    description: Setting up DevOps and quality tools
    
  - title: Phase 4 - Documentation
    description: Comprehensive documentation and examples
