name: Modular Remix Project Board
description: Default project board template for organizing tasks and tracking progress

columns:
  - name: To Do
    description: Tasks that need to be worked on
    
  - name: In Progress
    description: Tasks currently being worked on
    
  - name: Review
    description: Tasks that need review
    
  - name: Done
    description: Completed tasks

labels:
  - name: bug
    color: d73a4a
    description: Something isn't working
    
  - name: enhancement
    color: a2eeef
    description: New feature or request
    
  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation
    
  - name: good first issue
    color: 7057ff
    description: Good for newcomers
    
  - name: help wanted
    color: 008672
    description: Extra attention is needed
    
  - name: priority-high
    color: d93f0b
    description: High priority task
    
  - name: priority-medium
    color: fbca04
    description: Medium priority task
    
  - name: priority-low
    color: 0e8a16
    description: Low priority task
