name = "mk-modular-remix"
main = "./packages/host/build/index.js"
compatibility_date = "2023-12-16"

[site]
bucket = "./packages/host/public"

[build]
command = "pnpm build"

[vars]
NODE_ENV = "production"
