name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install dependencies
        run: pnpm install

      # Build shared modules first
      - name: Build shared package
        working-directory: packages/shared
        run: pnpm build

      - name: Build module1
        working-directory: packages/module1
        run: pnpm build

      - name: Build module2
        working-directory: packages/module2
        run: pnpm build

      # Finally build and deploy host
      - name: Build and deploy host
        if: github.ref == 'refs/heads/main'
        working-directory: packages/host
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: |
          pnpm deploy:production
