name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/host
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install dependencies
        run: |
          cd ../..
          pnpm install
        
      - name: Clean previous builds
        run: rm -rf build public/build
        
      - name: Build
        run: pnpm build

      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: |
            packages/host/build
            packages/host/public/build
          key: ${{ runner.os }}-build-${{ github.sha }}

  deploy-production:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/host
    environment: production
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install dependencies
        run: |
          cd ../..
          pnpm install

      - name: Restore build artifacts
        uses: actions/cache@v3
        with:
          path: |
            packages/host/build
            packages/host/public/build
          key: ${{ runner.os }}-build-${{ github.sha }}
        
      - name: Deploy to Cloudflare Workers
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: |
          echo "Using production configuration..."
          pnpm deploy:production
          
      - name: Verify Deployment
        run: |
          echo " Deployed to https://mk-modular-remix.direstrepobr.workers.dev"
          curl -s -o /dev/null -w "%{http_code}" https://mk-modular-remix.direstrepobr.workers.dev
