name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install dependencies
        run: pnpm install

      # Primero construimos shared ya que otros módulos dependen de él
      - name: Build shared package
        run: |
          cd packages/shared
          pnpm build
          cd ../..

      # Luego construimos todos los módulos
      - name: Build modules
        run: |
          cd packages/modules
          for module in *; do
            if [ -d "$module" ]; then
              cd "$module"
              pnpm build
              cd ..
            fi
          done
          cd ../..

      # Finalmente desplegamos host usando el mismo comando que funciona en local
      - name: Deploy to production
        if: github.ref == 'refs/heads/main'
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: |
          cd packages/host
          pnpm deploy:production
