name: CI

on:
  push:
    branches: [ dev, feature/*, fix/* ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
        
    - name: Install dependencies
      run: pnpm install
      
    - name: Type check
      run: pnpm typecheck
      
    - name: Lint
      run: pnpm lint
      
    - name: Test
      run: pnpm test
      
    - name: Build
      run: pnpm build
