name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install dependencies
        run: |
          pnpm install
          pnpm add -D tailwindcss-animate

      - name: Build shared modules
        run: |
          cd packages/shared
          pnpm build
          cd ../module1
          pnpm build
          cd ../module2
          pnpm build
        
      - name: Build host
        run: |
          cd packages/host
          rm -rf build public/build
          pnpm build

      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: |
            packages/host/build
            packages/host/public/build
          key: ${{ runner.os }}-build-${{ github.sha }}

  deploy-production:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install dependencies
        run: |
          pnpm install
          pnpm add -D tailwindcss-animate

      - name: Restore build artifacts
        uses: actions/cache@v3
        with:
          path: |
            packages/host/build
            packages/host/public/build
          key: ${{ runner.os }}-build-${{ github.sha }}
        
      - name: Deploy to Cloudflare Workers
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: |
          cd packages/host
          pnpm deploy:production
          
      - name: Verify Deployment
        run: |
          echo " Deployed to https://mk-modular-remix.direstrepobr.workers.dev"
          sleep 30  # Dar tiempo a que el despliegue se propague
          curl -s -o /dev/null -w "%{http_code}" https://mk-modular-remix.direstrepobr.workers.dev
